export enum TipoEventoEnum {
  AUDIENCIA = 'AUDIENCIA',
  SENTENCA = 'SENTENCA',
  RECURSO = 'RECURSO',
  DESPACHO = 'DESPACHO',
  PROTOCOLO = 'PROTOCOLO',
  PERICIA = 'PERICIA',
  ACORDO = 'ACORDO',
  OUTROS = 'OUTROS',
}
